name: uorf-variant-analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pandas=1.5.1
  - numpy=1.23.4
  - pysam=0.19.1
  - pybedtools=0.9.0
  - bedtools=2.30.0
  - biopython=1.80
  - pip:
    - pyranges==0.0.120
    - logging-formatter-anticrlf==1.2
